--- 
- name: Creating Internet Gateway
  hosts: localhost
  connection: local
  tasks: 
    - name: Generate random VPC ID
      set_fact:
        random_vpc_id: "vpc-{{ 100 + (ansible_play_batch.index * 10) | random(start=1, end=10) }}"

    - name: Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ random_vpc_id }}"
        state: present